# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 634490c1be0b0e57b126cabd792cef2b83a8d3cf79acf7b421562031762107fe89d7db0bafd78f1c6488e98d24ddec382f9ff794fe67f3c494f6516aa5f68055

test:
  secret_key_base: eb2678e54c5b0864e5a80b98583a505e418d0fe04d931867f9750dc70395804836820be986d59f384ed9cb0721ea0a4c90fabbb275ea6b3d9016b07ec7a494e1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
